data = [
    # Politik
    ("Pemerintah menetapkan kebijakan baru tentang pajak", "politik"),
    ("Menteri keuangan umumkan anggaran negara", "politik"),
    ("Pemilu presiden akan digelar tahun depan", "politik"),
    ("Pemerintah bahas subsidi BBM dalam sidang kabinet", "politik"),
    ("DPR mengesahkan undang-undang baru", "politik"),
    ("Presiden menghadiri konferensi tingkat tinggi ASEAN", "politik"),
    ("Menteri luar negeri bertemu dengan duta besar Amerika", "politik"),
    ("Kebijakan luar negeri Indonesia semakin proaktif", "politik"),
    ("Partai politik mulai kampanye menjelang pemilu", "politik"),
    ("Isu korupsi kembali mencuat di parlemen", "politik"),
    ("Pemerintah menetapkan kebijakan baru tentang pajak", "politik"),
    ("Menteri keuangan umumkan anggaran negara", "politik"),
    ("Pemilu presiden akan digelar tahun depan", "politik"),
    ("Pemerintah bahas subsidi BBM dalam sidang kabinet", "politik"),
    ("DPR mengesahkan undang-undang baru", "politik"),
    ("Presiden menghadiri konferensi tingkat tinggi ASEAN", "politik"),
    ("Menteri luar negeri bertemu dengan duta besar Amerika", "politik"),
    ("Kebijakan luar negeri Indonesia semakin proaktif", "politik"),
    ("Partai politik mulai kampanye menjelang pemilu", "politik"),
    ("Isu korupsi kembali mencuat di parlemen", "politik"),
    ("KPU menetapkan daftar pemilih tetap untuk pemilu", "politik"),
    ("Polemik revisi UU KPK kembali mencuat", "politik"), 
    ("Presiden resmikan UU Perlindungan Data Pribadi", "politik"),
    ("DPR setujui kenaikan anggaran pertahanan tahun 2025", "politik"),
    ("Partai oposisi gelar kampanye besar di Jakarta", "politik"),
    ("Pemilu daerah serentak akan digelar November mendatang", "politik"),
    ("Menteri luar negeri hadiri konferensi ASEAN di Manila", "politik"),
    ("Isu reshuffle kabinet kembali mencuat di media nasional", "politik"),
    ("Komisi antikorupsi tangkap pejabat tinggi kementerian", "politik"),
    ("Pemerintah dorong otonomi daerah melalui revisi UU", "politik"),
    ("KPU mulai distribusikan logistik pemilu ke daerah", "politik"),
    ("Mahkamah Konstitusi tolak gugatan hasil pilkada", "politik"),
    ("Rapat paripurna bahas revisi UU Pemilu", "politik"),
    ("Presiden tunjuk menteri baru bidang pertanian", "politik"),
    ("KPK sita aset senilai miliaran dari kasus korupsi", "politik"),
    ("Pemerintah bahas kerja sama pertahanan dengan Jepang", "politik"),
    ("Menteri perhubungan kunjungi proyek IKN", "politik"),
    ("Oposisi kritik kebijakan subsidi BBM terbaru", "politik"),
    ("Bali tuan rumah forum parlemen dunia", "politik"),
    ("RUU Perlindungan Perempuan disahkan DPR", "politik"),
    ("Kepala daerah baru dilantik di lima provinsi", "politik"),
    ("Presiden keluarkan Perppu tentang Pajak Digital", "politik"),
    ("Komisi I bahas regulasi keamanan siber nasional", "politik"),
    ("Mendagri tegaskan netralitas ASN dalam pemilu", "politik"),
    ("Rencana revisi UU ITE menuai pro dan kontra", "politik"),
    ("Presiden kunjungi Uni Eropa untuk kerja sama strategis", "politik"),
    ("Menteri sosial tinjau langsung lokasi bencana", "politik"),
    ("Ombudsman keluarkan rekomendasi soal pelayanan publik", "politik"),
    ("Dubes baru Indonesia untuk AS resmi dilantik", "politik"),
    ("Pemerintah kembangkan sistem e-voting nasional", "politik"),
    ("TNI laksanakan operasi gabungan di wilayah perbatasan", "politik"),
    ("Presiden terima kunjungan kenegaraan dari Korea Selatan", "politik"),
    ("Kebijakan subsidi pangan ditingkatkan untuk 2025", "politik"),
    ("Pemerintah kaji penghapusan jabatan wakil menteri", "politik"),
    ("Kemenlu kutuk agresi militer di wilayah konflik", "politik"),
    ("Rapat koordinasi nasional bahas bencana alam", "politik"),
    ("RUU Kesehatan disahkan meski menuai kontroversi", "politik"),
    ("Pemerintah tingkatkan pengawasan dana desa", "politik"),
    ("KPU gelar simulasi pemungutan suara elektronik", "politik"),
    ("Menteri ESDM bahas transisi energi di forum global", "politik"),
    ("Presiden lantik kepala lembaga baru bidang inovasi", "politik"),
    ("Koalisi baru dibentuk jelang pemilu presiden", "politik") ,  
    ("Dudung soal Masuk Bursa Calon Ketua Umum PPP: Tidak Berminat", "politik") ,  
    ("Daftar 5 Negara dengan Utang Terbesar ke China", "politik") ,  
    ("Wamenkum: Suka Tak Suka, RUU KUHAP Harus Disahkan 2025 Ini", "politik") ,  
    # Olahraga
    ("Barcelona menang 3-0 melawan Real Madrid", "olahraga"),
    ("Benzema mencetak hat-trick untuk Real Madrid", "olahraga"),
    ("Liverpool juara liga champions musim ini", "olahraga"),
    ("Timnas Indonesia lolos ke final AFF", "olahraga"),
    ("Cristiano Ronaldo pindah ke klub Arab Saudi", "olahraga"),
    ("Pemain muda Indonesia tampil impresif di SEA Games", "olahraga"),
    ("Turnamen bulu tangkis All England berlangsung seru", "olahraga"),
    ("Piala Dunia U-20 dibatalkan di Indonesia", "olahraga"),
    ("Persib Bandung menang dramatis lewat adu penalti", "olahraga"),
    ("Atlet renang Indonesia pecahkan rekor nasional", "olahraga"),
    ("Barcelona menang 3-0 melawan Real Madrid", "olahraga"),
    ("Benzema mencetak hat-trick untuk Real Madrid", "olahraga"),
    ("Liverpool juara liga champions musim ini", "olahraga"),
    ("Timnas Indonesia lolos ke final AFF", "olahraga"),
    ("Cristiano Ronaldo pindah ke klub Arab Saudi", "olahraga"),
    ("Pemain muda Indonesia tampil impresif di SEA Games", "olahraga"),
    ("Turnamen bulu tangkis All England berlangsung seru", "olahraga"),
    ("Piala Dunia U-20 dibatalkan di Indonesia", "olahraga"),
    ("Persib Bandung menang dramatis lewat adu penalti", "olahraga"),
    ("Atlet renang Indonesia pecahkan rekor nasional", "olahraga"),
    ("Pelatih baru timnas Indonesia resmi diumumkan", "olahraga"),
    ("Pertandingan tinju dunia berlangsung di Las Vegas", "olahraga"),
    ("Tim voli putri Indonesia raih perak di ASEAN Games", "olahraga"),
    ("Messi cetak gol kemenangan PSG", "olahraga"),
    ("Kejuaraan dunia MotoGP digelar di Mandalika", "olahraga"), 
    ("Timnas U-23 Indonesia kalahkan Vietnam di semifinal SEA Games", "olahraga"),
    ("Manchester City raih juara Liga Inggris musim ini", "olahraga"),
    ("Pebulutangkis Indonesia melaju ke final All England", "olahraga"),
    ("FIFA tetapkan Indonesia sebagai tuan rumah Piala Dunia U-20", "olahraga"),
    ("Cristiano Ronaldo cetak hattrick untuk Al Nassr", "olahraga"),
    ("Lionel Messi resmi bergabung dengan Inter Miami", "olahraga"),
    ("Persija Jakarta menang dramatis atas Persib Bandung", "olahraga"),
    ("Pebalap MotoGP Marc Marquez alami kecelakaan di sirkuit Mugello", "olahraga"),
    ("Petenis Novak Djokovic raih gelar Grand Slam ke-24", "olahraga"),
    ("Indonesia raih emas di cabang panahan Asian Games", "olahraga"),
    ("Atlet angkat besi Indonesia pecahkan rekor dunia", "olahraga"),
    ("Real Madrid lolos ke final Liga Champions Eropa", "olahraga"),
    ("LeBron James jadi top skor sepanjang masa NBA", "olahraga"),
    ("Timnas Futsal Indonesia ungguli Malaysia 5-1", "olahraga"),
    ("Valentino Rossi diumumkan masuk Hall of Fame MotoGP", "olahraga"),
    ("Atlet paralimpik Indonesia sabet medali emas di Tokyo", "olahraga"),
    ("Piala AFF 2024 akan digelar di Thailand", "olahraga"),
    ("Chelsea rekrut pelatih baru dari Argentina", "olahraga"),
    ("Atlet panjat tebing Indonesia juara dunia", "olahraga"),
    ("Tim voli putri Indonesia kalahkan Vietnam di final SEA Games", "olahraga"),
    ("Barcelona teken kontrak pemain muda berbakat asal Brasil", "olahraga"),
    ("MotoGP Mandalika sukses digelar tanpa kendala", "olahraga"),
    ("Tim e-sport Indonesia juara dunia Mobile Legends", "olahraga"),
    ("Kualifikasi Piala Asia: Indonesia ditahan imbang Singapura", "olahraga"),
    ("Liverpool dan Arsenal bersaing ketat di puncak klasemen EPL", "olahraga"),
    ("Anthony Ginting masuk peringkat 3 dunia BWF", "olahraga"),
    ("Atlet renang Indonesia pecahkan rekor Asia Tenggara", "olahraga"),
    ("Federasi Sepak Bola Asia beri sanksi ke pemain Thailand", "olahraga"),
    ("Serena Williams umumkan pensiun dari dunia tenis", "olahraga"),
    ("Arema FC meraih kemenangan penting atas PSIS Semarang", "olahraga"),
    ("EDUSPORTS: Apa Itu UEFA Badge of Honour?", "olahraga"),
    ("Ranking Klub UEFA Terbaru: AS Roma Peringkat 5 dan Manchester United Peringkat 14, Kok. Sah!", "olahraga"),
    ("Inter Milan raih Coppa Italia usai kalahkan Juventus", "olahraga"),
    ("Tim basket Indonesia melaju ke semifinal FIBA Asia", "olahraga"),
    ("Indonesia raih perunggu dalam Kejuaraan Dunia Karate", "olahraga"),
    ("Juventus ditarik 10 poin karena pelanggaran finansial", "olahraga"),
    ("Federasi tinju dunia ubah sistem penilaian pertandingan", "olahraga"),
    ("Atlet skateboard Indonesia tembus kualifikasi Olimpiade", "olahraga"),
    ("Pelatih timnas Indonesia janji bawa tim ke Piala Asia", "olahraga"),
    ("Perenang muda Indonesia raih emas di ASEAN School Games", "olahraga"),
    ("Duel panas antara AC Milan vs Napoli berakhir imbang", "olahraga"),
    ("Pelari Indonesia raih emas dalam lomba lari 100m SEA Games", "olahraga"),
    ("Malik Risaldi Senang Jadi Bek dan Bisa Kantongi Penyerang MU", "olahraga"),
    ("Erick Balas Sindiran Media Asing soal Naturalisasi Indonesia", "olahraga"),
    ("FIFA Akhirnya Buka Suara soal Rumput JIS", "olahraga"),
    ("Jelang PSG vs Inter, Inzaghi Diklaim Sepakat Gabung Al Hilal", "olahraga"),
    # Ekonomi
    ("Harga minyak dunia turun drastis hari ini", "ekonomi"),
    ("IHSG naik karena investor asing masuk", "ekonomi"),
    ("Kurs rupiah melemah terhadap dolar AS", "ekonomi"),
    ("Investasi asing meningkat di sektor teknologi", "ekonomi"),
    ("Pertumbuhan ekonomi kuartal kedua mencapai 5%", "ekonomi"),
    ("BPS mencatat inflasi turun pada bulan Mei", "ekonomi"),
    ("Bank Indonesia menaikkan suku bunga acuan", "ekonomi"),
    ("Nilai ekspor Indonesia meningkat tajam", "ekonomi"),
    ("Indeks harga konsumen stabil selama triwulan ini", "ekonomi"),
    ("Pasar saham Asia alami koreksi signifikan", "ekonomi"),
    ("Harga minyak dunia turun drastis hari ini", "ekonomi"),
    ("IHSG naik karena investor asing masuk", "ekonomi"),
    ("Kurs rupiah melemah terhadap dolar AS", "ekonomi"),
    ("Investasi asing meningkat di sektor teknologi", "ekonomi"),
    ("Pertumbuhan ekonomi kuartal kedua mencapai 5%", "ekonomi"),
    ("BPS mencatat inflasi turun pada bulan Mei", "ekonomi"),
    ("Bank Indonesia menaikkan suku bunga acuan", "ekonomi"),
    ("Nilai ekspor Indonesia meningkat tajam", "ekonomi"),
    ("Indeks harga konsumen stabil selama triwulan ini", "ekonomi"),
    ("Pasar saham Asia alami koreksi signifikan", "ekonomi"),
    ("Pemerintah keluarkan stimulus ekonomi baru", "ekonomi"),
    ("Perusahaan rintisan teknologi raih pendanaan besar", "ekonomi"),
    ("Nilai tukar rupiah menguat di akhir perdagangan", "ekonomi"),
    ("Inflasi Indonesia turun ke level 2,6% pada Mei 2025", "ekonomi"),
    ("Bank Indonesia pertahankan suku bunga acuan di 6,25%", "ekonomi"),
    ("Nilai tukar rupiah menguat terhadap dolar AS hari ini", "ekonomi"),
    ("Harga emas batangan Antam naik ke Rp1,18 juta per gram", "ekonomi"),
    ("IHSG ditutup menguat di level 7.200 pada penutupan perdagangan", "ekonomi"),
    ("Pemerintah umumkan subsidi listrik untuk golongan rumah tangga", "ekonomi"),
    ("Ekspor komoditas nikel capai rekor tertinggi sepanjang sejarah", "ekonomi"),
    ("Pertumbuhan ekonomi kuartal pertama 2025 capai 5,1%", "ekonomi"),
    ("Menteri Keuangan pastikan APBN 2025 tetap sehat dan kredibel", "ekonomi"),
    ("Startup teknologi Indonesia tarik investasi asing senilai $200 juta", "ekonomi"),
    ("Harga minyak dunia anjlok akibat over supply dari OPEC", "ekonomi"),
    ("Pemerintah gelontorkan bantuan UMKM senilai Rp15 triliun", "ekonomi"),
    ("BI luncurkan sistem pembayaran QRIS lintas negara ASEAN", "ekonomi"),
    ("Perdagangan karbon resmi dimulai di bursa Indonesia", "ekonomi"),
    ("IMF revisi proyeksi ekonomi global tahun 2025 menjadi 3,2%", "ekonomi"),
    ("Pemerintah tetapkan pajak karbon mulai berlaku 2025", "ekonomi"),
    ("Investasi asing langsung naik 12% sepanjang Q1 2025", "ekonomi"),
    ("Harga beras naik 3% menjelang Idul Adha", "ekonomi"),
    ("Pemerintah wacanakan penghapusan pajak sepeda listrik", "ekonomi"),
    ("Kurs rupiah dipengaruhi oleh sentimen pasar global", "ekonomi"),
    ("Kenaikan UMR 2025 disambut positif oleh buruh", "ekonomi"),
    ("OJK cabut izin operasional dua koperasi bermasalah", "ekonomi"),
    ("Laju kredit perbankan tumbuh 9% secara tahunan", "ekonomi"),
    ("Investor asing dominasi pasar obligasi pemerintah", "ekonomi"),
    ("Harga daging sapi impor turun karena kelonggaran bea masuk", "ekonomi"),
    ("Kementerian Keuangan targetkan pajak digital naik 15%", "ekonomi"),
    ("Rencana kenaikan PPN menjadi 12% menuai pro dan kontra", "ekonomi"),
    ("Rupiah menguat tipis seiring penguatan harga komoditas", "ekonomi"),
    ("Ekonomi digital diproyeksi tumbuh 19% pada 2025", "ekonomi"),
    ("Perusahaan logistik nasional buka ekspansi ke Asia Tenggara", "ekonomi"),
    ("Penjualan mobil listrik melonjak berkat insentif pajak", "ekonomi"),
    ("Pemerintah realisasikan anggaran infrastruktur Rp70 triliun", "ekonomi"),
    ("Sektor pariwisata menyumbang Rp450 triliun ke PDB 2024", "ekonomi"),
    ("Bursa kripto Indonesia makin diminati investor ritel", "ekonomi"),
    ("Pemerintah umumkan relaksasi pajak untuk startup teknologi", "ekonomi"),
    ("Kredit perumahan rakyat ditingkatkan untuk kalangan milenial", "ekonomi"),
    ("Indonesia ajukan kerja sama perdagangan dengan Uni Eropa", "ekonomi"),
    ("Konsumen mulai beralih ke produk lokal karena harga global naik", "ekonomi"),
    ("Pemerintah perketat pengawasan transaksi e-commerce luar negeri", "ekonomi"),
    ("Kementerian Perdagangan batasi impor barang konsumsi", "ekonomi"),
    ("Daftar 6 Insentif Prabowo Bulan Depan: Diskon Tarif Listrik hingga Tol", "ekonomi"),
    ("Penasihat Danantara Ray Dalio Terbitkan Buku Utang dan Negara Bangkrut", "ekonomi"),
    ("Ray Dalio Singgung Trump, Hitler-Mussolini di Buku Negara Bangkrut", "ekonomi"),
    ("Mensesneg Gugat Perusahaan Pontjo Sutowo Rp739 M, Kasus Apa?", "ekonomi"),
    #otomotif
    ("Toyota meluncurkan mobil listrik terbaru di Indonesia", "otomotif"),
    ("Honda resmi rilis motor listrik untuk pasar Asia", "otomotif"),
    ("Penjualan mobil SUV meningkat pesat tahun ini", "otomotif"),
    ("Tesla buka pabrik baru di India untuk produksi mobil listrik", "otomotif"),
    ("Pameran otomotif GIIAS 2025 dipadati pengunjung", "otomotif"),
    ("BMW umumkan strategi elektrifikasi seluruh lini kendaraan", "otomotif"),
    ("Kendaraan hybrid semakin diminati di pasar Eropa", "otomotif"),
    ("Industri otomotif nasional tumbuh 7 persen", "otomotif"),
    ("Yamaha rilis motor sport edisi terbatas", "otomotif"),
    ("Pemerintah akan beri insentif untuk pembelian mobil listrik", "otomotif"),
    ("Suzuki luncurkan mobil keluarga dengan fitur keselamatan terbaru", "otomotif"),
    ("Kawasaki siapkan motor off-road terbaru untuk pasar Indonesia", "otomotif"),
    ("Mobil listrik Wuling Air EV laris manis di pasar lokal", "otomotif"),
    ("Ford kembangkan teknologi mobil swakemudi generasi baru", "otomotif"),
    ("Ban ramah lingkungan mulai diproduksi massal", "otomotif"),
    ("Mitsubishi kenalkan konsep mobil SUV masa depan", "otomotif"),
    ("Kemenperin dorong produksi mobil listrik lokal", "otomotif"),
    ("Harga mobil bekas turun menjelang lebaran", "otomotif"),
    ("Motor listrik lokal Esemka siap dipasarkan", "otomotif"), 
    ("Toyota luncurkan Innova EV 2025 dengan jarak tempuh 600 km", "otomotif"),
    ("Honda kenalkan mobil listrik murah untuk pasar Asia Tenggara", "otomotif"),
    ("Pemerintah tambah insentif kendaraan listrik di 2025", "otomotif"),
    ("BMW iX2 resmi masuk Indonesia, harga mulai Rp1,5 miliar", "otomotif"),
    ("Tesla buka pabrik perakitan mobil listrik di Jawa Barat", "otomotif"),
    ("Penjualan motor listrik naik 78% selama kuartal pertama 2025", "otomotif"),
    ("Hyundai Ioniq 6 jadi mobil listrik paling laris di semester awal 2025", "otomotif"),
    ("Kemenhub wajibkan uji emisi tahunan mulai Juli 2025", "otomotif"),
    ("Mitsubishi XForce Hybrid mulai diproduksi di Indonesia", "otomotif"),
    ("Perodua Axia EV akan jadi rival terkuat Wuling Air EV", "otomotif"),
    ("Pasar mobil bekas meningkat 25% akibat inflasi", "otomotif"),
    ("Mazda rilis crossover CX-80 di pasar Asia", "otomotif"),
    ("Honda City facelift 2025 hadir dengan fitur ADAS lengkap", "otomotif"),
    ("Yamaha perkenalkan motor listrik E01 versi komersial", "otomotif"),
    ("Wuling Air EV ekspor perdana ke Australia dan Filipina", "otomotif"),
    ("BMW kenalkan fitur autopilot Level 3 untuk pasar Indonesia", "otomotif"),
    ("Tesla Model Y facelift akan masuk pasar ASEAN akhir 2025", "otomotif"),
    ("Hyundai bangun stasiun pengisian EV super cepat di Jakarta", "otomotif"),
    ("Penjualan kendaraan hybrid naik tajam di tengah transisi EV", "otomotif"),
    ("Pemerintah akan gratiskan STNK untuk motor listrik mulai 2025", "otomotif"),
    ("Industri otomotif lokal dorong penggunaan baterai buatan dalam negeri", "otomotif"),
    ("DFSK Glory E3 jadi SUV listrik murah alternatif Tesla", "otomotif"),
    ("Suzuki kenalkan XL7 Hybrid 2025 dengan efisiensi tinggi", "otomotif"),
    ("Astra buka pusat pelatihan mekanik khusus EV di Cikarang", "otomotif"),
    ("Regulasi kendaraan otonom mulai disusun oleh Kemenhub", "otomotif"),
    ("Oli EV khusus diluncurkan oleh Pertamina Lubricants", "otomotif"),
    ("Toyota akan hentikan produksi mesin bensin murni pada 2026", "otomotif"),
    ("VinFast resmi ekspansi mobil listrik ke Indonesia tahun 2025", "otomotif"),
    ("Industri modifikasi EV mulai berkembang di kalangan milenial", "otomotif"),
    ("Wuling perkenalkan sistem baterai swap untuk Air EV", "otomotif"),
    ("Pemerintah wajibkan kendaraan dinas baru harus EV mulai 2026", "otomotif"),
    ("Honda BeAT 2025 hadir dengan teknologi mild-hybrid", "otomotif"),
    ("Rantai pasok chip otomotif dunia kembali terganggu oleh geopolitik", "otomotif"),
    ("Tesla buka jaringan Supercharger publik di Jakarta dan Bandung", "otomotif"),
    ("BYD mulai bangun pabrik mobil listrik di Batang, Jawa Tengah", "otomotif"),
    ("Omoda 5 EV resmi dirakit lokal di Indonesia mulai Agustus 2025", "otomotif"),
    ("Dealer motor listrik tumbuh pesat di luar Pulau Jawa", "otomotif"),
    ("Volvo XC90 EV 2025 dibuka pre-order dengan fitur pengemudi otonom", "otomotif"),
    ("BMW akan gunakan panel surya untuk charging station EV-nya", "otomotif"),
    ("Konsumen otomotif Indonesia mulai transisi ke EV berukuran kecil", "otomotif"),
    #teknologi
    ("Google memperkenalkan fitur AI terbaru di Google Search", "teknologi"),
    ("Startup AI lokal raih pendanaan sebesar 10 juta dolar", "teknologi"),
    ("Apple rilis iPhone 16 dengan fitur kamera super canggih", "teknologi"),
    ("Indonesia akan bangun pusat data nasional tahun ini", "teknologi"),
    ("Microsoft umumkan pembaruan besar untuk Windows 12", "teknologi"),
    ("Facebook ubah nama menjadi Meta dan fokus ke metaverse", "teknologi"),
    ("Perusahaan rintisan bidang edutech semakin berkembang", "teknologi"),
    ("Pemerintah dorong transformasi digital di sektor UMKM", "teknologi"),
    ("Samsung luncurkan layar lipat generasi ketiga", "teknologi"),
    ("Kaspersky deteksi serangan siber besar-besaran ke Asia Tenggara", "teknologi"),
    ("ChatGPT kini bisa digunakan dalam lebih dari 30 bahasa", "teknologi"),
    ("Instagram uji coba fitur berbasis kecerdasan buatan", "teknologi"),
    ("TikTok tambah fitur keamanan untuk remaja", "teknologi"),
    ("Penetrasi internet di Indonesia capai 78 persen", "teknologi"),
    ("Teknologi 6G sedang dikembangkan oleh beberapa negara", "teknologi"),
    ("Huawei kenalkan chipset baru dengan performa tinggi", "teknologi"),
    ("Apple Vision Pro akan tersedia global akhir tahun ini", "teknologi"),
    ("Perusahaan teknologi berlomba-lomba masuk ke pasar AI", "teknologi"),
    ("Indonesia siapkan regulasi baru untuk AI dan big data", "teknologi"),
    ("Startup fintech tumbuh cepat pasca pandemi", "teknologi"),
    ("Apple umumkan Vision Pro akan rilis global pada akhir 2025", "teknologi"),
    ("Google luncurkan Android 15 dengan fitur privasi lanjutan", "teknologi"),
    ("OpenAI rilis GPT-5 dengan peningkatan reasoning dan memori jangka panjang", "teknologi"),
    ("Samsung Galaxy Z Fold 6 hadir dengan desain lebih tipis dan tahan air", "teknologi"),
    ("Indonesia bangun pusat AI nasional untuk mendukung industri 4.0", "teknologi"),
    ("Microsoft umumkan Copilot Pro untuk produktivitas AI di Office 365", "teknologi"),
    ("Tesla kembangkan chip Dojo generasi kedua untuk pelatihan AI", "teknologi"),
    ("Apple M4 chip diklaim 40% lebih cepat dari generasi sebelumnya", "teknologi"),
    ("Meta luncurkan Meta Quest 4 dengan pelacakan mata tingkat lanjut", "teknologi"),
    ("TikTok rilis fitur AI Avatar untuk pembuat konten", "teknologi"),
    ("Google DeepMind umumkan Gemini 2 sebagai pesaing GPT-5", "teknologi"),
    ("ASUS ROG Phone 9 jadi smartphone gaming pertama dengan sistem pendingin cair mini", "teknologi"),
    ("BYD perkenalkan sistem infotainment EV berbasis Android Auto AI", "teknologi"),
    ("Netflix hadirkan fitur AI Dubbing untuk film dan serial global", "teknologi"),
    ("Startup Indonesia kembangkan drone pertanian dengan pemetaan AI", "teknologi"),
    ("AMD rilis GPU MI325X untuk akselerasi AI di pusat data", "teknologi"),
    ("Xiaomi 15 Ultra hadir dengan kamera Leica dan fitur AI Scene Detection", "teknologi"),
    ("Sony kenalkan kamera Alpha 9 III dengan shutter global pertama di dunia", "teknologi"),
    ("Telegram tambahkan fitur AI bot untuk bantu balas otomatis pesan", "teknologi"),
    ("Google Translate kini gunakan AI multimodal untuk akurasi lebih tinggi", "teknologi"),
    ("Perusahaan Indonesia bangun satelit internet orbit rendah (LEO)", "teknologi"),
    ("Microsoft Edge hadir dengan fitur pembaca artikel berbasis suara AI", "teknologi"),
    ("OpenAI perkenalkan voice assistant mirip Jarvis untuk ChatGPT", "teknologi"),
    ("Instagram uji coba fitur AI auto-caption dengan dukungan banyak bahasa", "teknologi"),
    ("Startup lokal buat platform pelatihan AI dalam Bahasa Indonesia", "teknologi"),
    ("Samsung kenalkan chip 3nm generasi kedua untuk efisiensi energi", "teknologi"),
    ("WhatsApp tambahkan fitur AI summarization untuk grup bisnis", "teknologi"),
    ("Tiktok Shop gunakan AI untuk rekomendasi produk real-time", "teknologi"),
    ("NASA gunakan machine learning untuk navigasi misi luar angkasa", "teknologi"),
    ("Baidu luncurkan Ernie Bot 5, pesaing ChatGPT di China", "teknologi"),
    ("LinkedIn integrasikan AI untuk bantu pengguna tulis CV dan cover letter", "teknologi"),
    ("iPhone 17 Pro diprediksi hadir dengan Neural Engine 2 untuk AI real-time", "teknologi"),
    ("Google Chrome tambahkan fitur AI Tab Organizer untuk pengguna multitasking", "teknologi"),
    ("Startup AI lokal rilis platform voice cloning berbahasa daerah", "teknologi"),
    ("Apple Music tambahkan fitur smart playlist dengan personalisasi AI", "teknologi"),
    ("Meta kenalkan model AI video generation pesaing Sora", "teknologi"),
    ("YouTube gunakan AI untuk auto-chapter dan terjemahan langsung", "teknologi"),
    ("OpenAI dan Stack Overflow kerja sama integrasikan coding assistant", "teknologi"),
    ("Samsung SmartThings dukung pengenalan suara multi-pengguna via AI", "teknologi"),
    ("Shopee tambahkan chatbot AI untuk bantu pembeli menemukan produk", "teknologi"),
    ("Kemkomdigi Raih Opini WTP atas Laporan Keuangan 2024", "teknologi"),
]
